#!/bin/bash
cd hw1_folder/
mkdir lesson_1 lesson_2 lesson_3
cd lesson_2
touch file1.txt file2.txt file3.txt file4.json file5.json
mkdir subfolder1 subfolder2 subfolder3
ls -la
mv file3.txt ./subfolder1/file3.txt
mv file5.json ./subfolder2/file5.json
